const ORDER_STATUS = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAID: "PAID",
  PREPARING: "PREPARING",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  READY_FOR_PICKUP: "READY_FOR_PICKUP",
  DELIVERED: "DELIVERED",
  RETURNED: "RETURNED",
  REFUNDED: "REFUNDED",
  CANCELED: "CANCELED",
};

const allowedTransitions = {
  [ORDER_STATUS.PENDING_PAYMENT]: [
    ORDER_STATUS.PAID,
    ORDER_STATUS.PAYMENT_FAILED,
    ORDER_STATUS.CANCELED,
  ],
  [ORDER_STATUS.PAID]: [
    ORDER_STATUS.PREPARING,
    ORDER_STATUS.OUT_FOR_DELIVERY,
    ORDER_STATUS.READY_FOR_PICKUP,
    ORDER_STATUS.REFUNDED,
    ORDER_STATUS.RETURNED,
    ORDER_STATUS.CANCELED,
  ],
  [ORDER_STATUS.PREPARING]: [
    ORDER_STATUS.OUT_FOR_DELIVERY,
    ORDER_STATUS.READY_FOR_PICKUP,
    ORDER_STATUS.RETURNED,
    ORDER_STATUS.CANCELED,
  ],
  [ORDER_STATUS.OUT_FOR_DELIVERY]: [ORDER_STATUS.DELIVERED, ORDER_STATUS.RETURNED],
  [ORDER_STATUS.READY_FOR_PICKUP]: [ORDER_STATUS.DELIVERED, ORDER_STATUS.RETURNED, ORDER_STATUS.CANCELED],
  [ORDER_STATUS.RETURNED]: [ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.PAYMENT_FAILED]: [
    ORDER_STATUS.CANCELED,
    ORDER_STATUS.PAID,
    ORDER_STATUS.PENDING_PAYMENT,
  ],
  [ORDER_STATUS.DELIVERED]: [],
  [ORDER_STATUS.REFUNDED]: [],
  [ORDER_STATUS.CANCELED]: [ORDER_STATUS.REFUNDED],
};

function canTransition(from, to) {
  return (allowedTransitions[from] || []).includes(to);
}

module.exports = {
  ORDER_STATUS,
  allowedTransitions,
  canTransition,
};
